apiVersion: v1
kind: Service
metadata:
  name: greeting-api
  namespace: default 
  labels:
    app: greeting-api-app
spec:
  selector:
    app: greeting-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
