name: ci-java-maven-docker-aws-ecr.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:

    - name: check out
      uses: actions/checkout@v3

    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: build jar with maven
      run: |
        ./mvnw clean package

    - name: build image with docker
      run: |
        docker build -t greeting-api-openjdk-17-oracle:0.0.1 .

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: login to aws ecr
      id: 'AWS'
      uses: aws-actions/amazon-ecr-login@v1

    - name: push image to aws ecr
      run: |
        hostname
        #docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/greeting-api-openjdk-17-oracle:0.0.1

